---
title: "My awesome website"
output: 
  html_document:
    toc: true
    toc_float: true
---


# Iris Hart

email (650)644-7915 [linkedin](https://www.linkedin.com/in/irishart/)

### Education
#### COLUMBIA UNIVERSITY Mailman School of Public Health                        
Master of Public Health - Epidemiology | New York, NY | Expected May 2025

Relevant Coursework - Research Methods & Applications, Health Systems, Health Econ, and Public Health Interventions

#### BOSTON UNIVERSITY                                                         
Bachelor of Science, Health Sciences | Boston, MA | May 2023

GPA: 3.7, Cum Laude

### Work Experience
#### Pfizer, Inc.	                        									
Medical Affairs Marketing Intern | 	New York, NY | June 2023-Aug 2023

•	Generated comprehensive literature reviews on prevalence rates for alopecia areata and aspergillosis, identifying key trends and gaps in emerging markets such as Brazil, UAE, Mexico, and Taiwan

•	Analyzed the impact of healthcare systems and environmental factors on disease prevalence, enhancing understanding of market dynamics and patient journey from diagnosis to treatment

•	Collaborated with cross-functional teams to compare Pfizer’s proprietary data with open-source information, ensuring accuracy and reliability in prevalence insights

#### Dana-Farber Cancer Institute - Dieli-Conwright Exercise Oncology Research Laboratory
Research Intern | Boston, MA | Sep 2022-Dec 2022

• Conducted screenings for 300 breast cancer patients using Epic Systems to assess eligibility for participation in the Adiposity
Inflammation Movement study, which investigates the impact of exercise on BMI reduction, and therefore breast cancer
outcomes

• Performed data entry duties for the AIM study using REDCap (data entry software)

• Managed and maintained patient evaluation forms, facilitating the measurement of patient satisfaction and the identification of
external factors affecting exercise capabilities

#### Brigham and Women’s Hospital - Channing Division of Network Medicine Research 
Research Coder | Boston, MA | June 2022 – Aug 2022

• Evaluated 500 Nurses' Health Study questionnaires through coding procedures in order to determine risk factors for major
chronic diseases in women. Identified risk factors will be used to investigate interventions for targeting major chronic diseases

• Administered follow-up surveys to previous study participants as part of ongoing research for the Nurses’ Health Study

• Structured and managed datasets evaluating health and lifestyle elements, including dietary habits, physical activity, and
adiposity

#### Stanford University School of Medicine - The Solutions Science Laboratory
Research Intern | Stanford, CA | June 2021 – Oct 2021

• Reduced the prevalence of obesity by 80% within participants in the Stanford Pediatric Weight Control Program, through
expansion of program materials such as exercise routines, healthy eating, and behavioral habits

• Upgraded the Pediatric Weight Control Program’s resource manual by streamlining the information and converting it to web-
based content

• Secured internship funding as a recipient of the Boston University Yawkey Nonprofit Internship Program Award

#### Stanford University School of Medicine - District Coding with Stanford Pediatrics 
Research Intern | Stanford, CA | June 2020 – May 2021

• Gathered data from California Public School District websites, social media pages, and local news sources pertaining to meal
service protocols during the COVID-19 school closures

• Systematically encoded pertinent information regarding the provision of meals by school districts, the accessibility of these
meals, and specific pickup instructions to determine which districts were in need of increased food related funding

### Leadership Experience
#### Undergraduate Public Health Association Executive Board Member 

President (2022-2023) | Activities Coordinator and Secretary (2021-2022) Aug 2021 –May 2023

• Expanded club participation by 50% through organized club activities, including volunteer opportunities for members to engage in
that orient around club’s mission of learning and educating one another on relevant public health issues

• Planned and conducted weekly discussions focused on pertinent public health topics such as breast cancer, sexual health,
environmental public health, career pathways, and post-graduate education

#### Sargent School of Health Peer Mentor 

Peer Mentor | Aug 2021 - May 2023

• Advised 3 intra-university and external transfer students in the Sargent School of Health over the course of one year

• Tailored resources and mentorship advice to mentees within Sargent school, while also coordinating academic events concerning
internships and research experience, study abroad, and how to be successful in academic courses

### Relevant Skills
•	SAS Software, R programming, REDCap Software, Epic Systems, logical reasoning, data analysis, critical thinking, teamwork
